---
#Use § For Color
#use \n For A New Line

#Message When Player it's not In-Game
console-msg: "§7[§c!§7] §cThis command can't be used here. Sorry!"

#Message When Player Quit The Menu
quit-msg: "§7[§c!§7] §eClosed Mask Menu..."
...
